version: "3"
services:
  web:
    # This build . means to build the dockerfile found in here
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /opt/mysql-counter:/counter_app
    links:
      # container will see it as mysql, but to us it is db container
      - db:mysql
    container_name: countersql_web_1
    # tells order of build, so build db first
    depends_on:
      - db
    
  db:
    image: mysql
    restart: always
    container_name: countersql_db_1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: counter
