version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /opt/mongodb-counter:/counter_app
    links:
      - db:mongodb
    container_name: countermongo_web_1
    depends_on:
      - db
    
  db:
    image: mongo
    restart: always
    container_name: countermongo_db_1
